# Generated by Django 2.2.1 on 2019-05-12 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
                ('Level', models.IntegerField()),
                ('CreatedBy', models.BigIntegerField()),
                ('CreatedTime', models.DateField(default=django.utils.timezone.now)),
                ('ModifiedBy', models.BigIntegerField()),
                ('ModifiedTime', models.DateField(default=django.utils.timezone.now)),
                ('IsDeleted', models.BooleanField()),
                ('DeletedBy', models.BigIntegerField()),
                ('DeletedTime', models.DateField(default=django.utils.timezone.now)),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Content', models.TextField()),
                ('Summary', models.TextField(max_length=300)),
                ('Resource', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='gallery')),
                ('View', models.BigIntegerField()),
                ('Tags', models.CharField(max_length=500)),
                ('PostStatus', models.SmallIntegerField()),
                ('CreatedBy', models.BigIntegerField()),
                ('CreatedTime', models.DateField(default=django.utils.timezone.now)),
                ('ModifiedBy', models.BigIntegerField()),
                ('ModifiedTime', models.DateField(default=django.utils.timezone.now)),
                ('IsDeleted', models.BooleanField()),
                ('DeletedBy', models.BigIntegerField()),
                ('DeletedTime', models.DateField(default=django.utils.timezone.now)),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
            ],
        ),
    ]
