# Generated by Django 2.2.1 on 2019-05-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190512_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='DeletedBy',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
