# Generated by Django 2.2.1 on 2019-05-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190512_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PostStatus',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='View',
            field=models.BigIntegerField(default=0),
        ),
    ]
