# Generated by Django 2.2.1 on 2019-05-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190512_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Image',
            new_name='Photo',
        ),
    ]
