# Generated by Django 2.2.1 on 2019-05-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190512_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('Id',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='Tags',
        ),
    ]
